#set this to true if you want to only see the commands that would be created
test: false 

#ensembl
ref: mus_musculus_core_55_37h
ensembl_host: ens-livemirror
ensembl_user: ensro
ensembl_port: 3306

pileup_das_track:
  host: ens-research
  user: ensadmin
  password: ensembl
  port: 3306
  database_name_prefix: mp4_pileup
  window_frequency: 1
  extended_length: 200

conservation_score_track:
  host: ens-research
  user: ensadmin
  password: ensembl
  port: 3306
  database_name: mp4_ncbim37_phastcons_v
  input_data_prefix: /nfs/th_group/mp4/phastcons/vertebrate/

mapping:
  mapping_quality_above: 10

peak_calling_method: macs

peak_calling:
  macs:
    effective_genome_size: 2500000000
    tag_size: 54
    pvalue: 1e-5 #default
    mfold: 20
    diagnosis: false
    bandwidth: 100
    nomodel: false
    shiftsize: 80

  swembl:
    fragment_length : 200
    penalty_factor: 1.5
    relative_background: 0.05

peak_seq_retrieval:
  around_peaks: 200 #output the sequence on either side of the peak maximum
  mask_repeats: true
  mask_translations: true
  max_count: 1000
  min_length: 20 #filter out peaks below the peak length
  max_length: 800 #filter out peaks above the peak length
  max_distance_from_gene: 2000
  min_non_n: 50
  ignore_xrefless: true

  #chunk_length: 200 #divide sequences to some max length

tss_seq_retrieval:
  upstream_nukes: 1500
  downstream_nukes: 1500

motif_discovery:
  nmica:
    mem: 2000
    cpus: 4
    background_classes: 4
    background_order: 1
    expected_usage_fraction: 0.5
    min_motif_length: 6
    max_motif_length: 14
    checkpoint_dir: checkpoints
    num_motifs: 8

scan_cutoff:
  background_model: bg/41.bg
  default_cutoff: 1.0

overrep_analysis:
  bootstraps: 100000


